version: '3.8'

services:
  web:
    build: ./app
    ports:
      - "5001:5000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=flask_db
      - DB_USER=flask_user
      - DB_PASSWORD=flask_pass

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: flask_db
      POSTGRES_USER: flask_user
      POSTGRES_PASSWORD: flask_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
